updated hauler `install.sh` and readme
hauler-dev/hauler pull request #152
Opened 2023-12-20 05:34 UTC by zackbradys

**Please check below, if the PR fulfills these requirements:**
- [X] The commit message follows the guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [X] Docs have been added / updated (for bug fixes / features).

**What kind of change does this PR introduce?**
* feature to improve handling of the `hauler` version in the `install.sh` script

**What is the current behavior?**
* the `install.sh` script defaults to a hard coded version.

**What is the new behavior (if this is a feature change)?**
* the `install.sh` script automatically defaults to the latest version of `hauler` in github

**Does this PR introduce a breaking change?**
* N/A

**Other information**:
* N/A

2023-12-20 13:42 UTC, amartin120 requested changes, later dismissed
Would you mind adding the homebrew instructions while you're here?  There's already a section on line 29.

2023-12-20 18:20 UTC, dweomer approved these changes

2023-12-21 00:53 UTC, zackbradys reviewed
updated for homebrew!

2023-12-21 00:56 UTC, amartin120 approved these changes

2023-12-21 00:56 UTC, merged