Added store copy examples and error information
hauler-dev/hauler pull request #239
Opened 2024-05-01 17:37 UTC by 55octet

**Please check below, if the PR fulfills these requirements:**
- [ x ] Commit(s) and code follow the repositories guidelines.
- [ ] Test(s) have been added or updated to support these change(s).
- [ ] Doc(s) have been added or updated to support these change(s).

**Associated Links:**

- 

**Types of Changes:**

- Add validation and examples around the store copy command as it is did not list registry:// or dir:// for the remote repo.

**Proposed Changes:**

- Add validation and examples around the `store copy` command

**Verification/Testing of Changes:**

- Run `hauler store copy` to display examples.

**Additional Context:**

- This should be a small change to make the cli experience usable without looking at the source code.

2024-05-01 17:41 UTC, 55octet commented
Based from https://github.com/rancherfederal/hauler/pull/238.

Signed my commit (hadn't updated my pgp on github) and ran `go fmt`.  I didn't notice any changes after formatting; it seems that `cmd/hauler/cli/store.go` wasn't formatted correctly.  If I am missing a format configuration, I can fix it.

2024-05-18 14:47 UTC, zackbradys commented
hey @55octet, thank you for your contribution to the project. taking a look at the examples in the subcommand, could you please update them to `registry://registry.example.com` and `dir://hauler-files`?

2024-05-18 14:49 UTC, zackbradys commented
@amartin120 please take a look at the error information and updated formatting.

2024-05-21 17:43 UTC, 55octet commented
Hi @zackbradys --

I will update and push today.

Thank you!!

2024-06-04 03:40 UTC, zackbradys commented
Hey @55octet, please update this PR when you get a chance so we can merge it!

2024-06-10 17:48 UTC, dweomer commented on cmd/hauler/cli/store/copy.go
These don't amount to meaningful changes and I would argue make the logic less clear in that it introduces a separate `if` conditional that was already handled in the still-relevant `switch` block.

2024-06-10 17:49 UTC, dweomer requested changes
The example text looks great. The other changes are unnecessary.

2024-08-26 16:13 UTC, dweomer commented on cmd/hauler/cli/store.go
>  )
can we get a `goimports --local -w` pass?

2024-09-17 23:05 UTC, closed without merging