Fix digest images being lost on load of hauls (Signed).
hauler-dev/hauler pull request #259
Opened 2024-06-30 20:11 UTC by KaminFay

**Please check below, if the PR fulfills these requirements:**
- [x] Commit(s) and code follow the repositories guidelines.
- [x] Test(s) have been added or updated to support these change(s).
- [x] Doc(s) have been added or updated to support these change(s).

**Associated Links:**

- #250 

**Types of Changes:**

- Bugfix

**Proposed Changes:**

### Note:
Had to republish the PR after fixing my laptops commit signing setup.

- Current when the image reference is taken by the `Pusher()` method and split, it is done so based on the first instance of the `@` symbol:
```go
var baseRef, hash string
parts := strings.SplitN(ref, "@", 2)
baseRef = parts[0]
if len(parts) > 1 {
    hash = parts[1]
}
```

- Proposed way of splitting:
```go
	var baseRef, hash string

	parts := strings.Split(ref, "@")
	baseRef = strings.Join(parts[:len(parts)-1], "@")
	if len(parts) > 1 {
		hash = parts[len(parts)-1]
	}

	return baseRef, hash
```

- In reality that will cause the hash to appear with a lot of extra junk if there is more than one `@` symbol in the reference string, like there is with digests.... Ex:
```
sha256:95b01e2e9ab0702ce2f1a8f05f90e6408fd1f4b5e5006c6088ba5a864ed42064-library/nginx@sha256:95b01e2e9ab0702ce2f1a8f05f90e6408fd1f4b5e5006c6088ba5a864ed42064-dev.cosignproject.cosign/imageIndex@sha256:95b01e2e9ab0702ce2f1a8f05f90e6408fd1f4b5e5006c6088ba5a864ed42064"
```

- The proposed solution will instead filter on the last `@` symbol instead of the first. Resulting in a proper hash being pulled out.
- A long with this the splitting on the hash and base reference string has been pulled out into its own function so that it can be tested using the newly included testing methods. Just to make sure digests are not broken again in the future.
**Verification/Testing of Changes:**

- The change can be verified by following the steps in the bug report and seeing that we now have the correct index on unpacking and the info command shows everything is where it should be.

2024-07-09 15:54 UTC, dweomer commented on pkg/content/oci_test.go
> +			"sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0",
these really threw me for a loop, i mean, "what in the wall of text?!"
so, i go to the image spec to prove you wrong via official docs (this insanity cannot be spec-compliant!) and what do i find? (see: https://github.com/opencontainers/image-spec/blob/v1.0.2/annotations.md#pre-defined-annotation-keys)
![image](https://github.com/rancherfederal/hauler/assets/1033444/3095b264-eca5-4641-a248-52feba3fb6d6)

CURSE YOU EBNF!!!1one

2024-07-09 16:22 UTC, dweomer commented on pkg/content/oci.go
> +func splitImageRef(ref string) (string, string) {
Would prefer to see something higher level, using https://github.com/distribution/reference if possible.

2024-07-09 16:24 UTC, dweomer requested changes
As noted [here](https://github.com/rancherfederal/hauler/pull/259/files#r1670834856) I would very much prefer we try a more standard approach and try to leverage https://github.com/distribution/reference for correctness if not concision.

2024-07-13 19:28 UTC, KaminFay commented on pkg/content/oci.go
> +func splitImageRef(ref string) (string, string) {
Sounds good, I'll take a look at this tonight / tomorrow to see what I can do!

2024-07-21 02:37 UTC, KaminFay commented on pkg/content/oci.go
> +func splitImageRef(ref string) (string, string) {
I've been looking into this off and on again over the last few days trying to wrap my brains around this issue as a whole. I was going to look into using the `distributions/reference` package but I didn't see an avenue to get there easily since it seems hauler is already using an internal reference package that wraps googles: [here](https://github.com/hauler-dev/hauler/blob/894ffb15336745d7856ff531ca0c961b314d5f77/pkg/reference/reference.go#L10C1-L11C1)

So I ended up looking into how hauler loads its index [here](https://github.com/hauler-dev/hauler/blob/894ffb15336745d7856ff531ca0c961b314d5f77/pkg/content/oci.go#L73C1-L79C1) which lead me to the generation of the key like this:

```go
for _, desc := range o.index.Manifests {
	key := fmt.Sprintf("%s-%s-%s", desc.Digest.String(), desc.Annotations[ocispec.AnnotationRefName], desc.Annotations[consts.KindAnnotationName])
	if strings.TrimSpace(key) != "--" {
		o.nameMap.Store(key, desc)
	}
}
```
- key: `sha256:<...>-neuvector/updater@sha256:0076b356368c9988eec5f3cead771d29a377074b982f22800f4d9c8c3b215a56-<kind>`

I picked that apart a bit end suddenly realized how we were ending up with such long keys `<digest>-<reference>-<kind>`. Opted to try and shorten that to use the internal reference package:

```go
ref, err := reference.Parse(desc.Annotations[ocispec.AnnotationRefName])
o.nameMap.Store(ref.Name(), desc)
```
- key: `neuvector/updater@sha256:0076b356368c9988eec5f3cead771d29a377074b982f22800f4d9c8c3b215a56`

The results were a bit better as the key was now a lot shorter, only downside is that it was still failing to pick up digests using the original split usage (which was duplicated from [the oras-go implementation](https://github.com/oras-project/oras-go/blob/9d9e2cb1efbad77745b57601947a3b537313ba7f/pkg/content/oci.go#L157C1-L168C2):

```go
	parts := strings.SplitN(ref, "@", 2)
	baseRef = parts[0]
	if len(parts) > 1 {
		hash = parts[1]
	}
```

- This is due to the fact that the actual call to `Pusher()` in this instance is from the oras-go library where it will always append the digest to the reference [code](https://github.com/oras-project/oras-go/blob/9d9e2cb1efbad77745b57601947a3b537313ba7f/pkg/oras/copy.go#L73C1-L74C1):

```go
	// construct the reference we send to the pusher using the digest, so it knows what the root is
	pushRef := fmt.Sprintf("%s@%s", toRef, desc.Digest.String())
	pusher, err := to.Pusher(ctx, pushRef)
	if err != nil {
		return ocispec.Descriptor{}, err
	}
```
- ref: `neuvector/updater@sha256:0076b356368c9988eec5f3cead771d29a377074b982f22800f4d9c8c3b215a56@sha256:0076b356368c9988eec5f3cead771d29a377074b982f22800f4d9c8c3b215a56`

So I think we have two possible answers:
1. Continue to split the reference after it is passed into `Pusher()` 
2. Better format the key to remove the digest before it gets sent to oras-go and gets the digest appended on to it
3. I am way off base on how this is supposed to function

2024-07-22 18:15 UTC, zackbradys commented on pkg/content/oci.go
> +func splitImageRef(ref string) (string, string) {
Hey @KaminFay, thanks for the background information and digging deeper into it. I'll make sure that we bring this up at our meeting later today!

2024-07-22 19:22 UTC, dweomer commented on pkg/content/oci.go
> +func splitImageRef(ref string) (string, string) {
> So I think we have two possible answers:
> 1. Continue to split the reference after it is passed into Pusher()
> 2. Better format the key to remove the digest before it gets sent to oras-go and gets the digest appended on to it
> 3. I am way off base on how this is supposed to function

I like (2) but it will have the side-effect, I think, of collapsing sha256 refs to tag refs (which shouldn't be a problem, I think).

2024-07-24 18:04 UTC, KaminFay commented on pkg/content/oci.go
> +func splitImageRef(ref string) (string, string) {
I can take a look at this over the next few days as time allows. I'll work towards implementing the second approach and see if there's any noticeable ramifications.

2024-07-29 03:13 UTC, KaminFay commented on pkg/content/oci.go
> +func splitImageRef(ref string) (string, string) {
Curious to see what you guys think of the changes I just pushed.

1. Reverted the string split back to what was originally there.
2. Adjusted the `AddIndex` and `LoadIndex` methods in OCI.go:
    1. Used the `reference.Parse()` method to load the key rather than string formats
    2. Switches based on key type of digest or tag and sets the key respecting those types, that way digest based keys no longer have the digest tacked onto the end of them before they get sent through `oras.Copy`

All regular and integration tasks passed with no issues. Manual tests of add / sync / save / load functioned with no issues.

2024-07-30 18:29 UTC, dweomer approved these changes

2024-07-30 19:29 UTC, zackbradys commented
Thanks for reviewing and approving @dweomer... will test this tonight before merging.

@KaminFay do you notice any issues?

2024-07-30 22:19 UTC, KaminFay commented
> Thanks for reviewing and approving @dweomer... will test this tonight before merging.
> 
> @KaminFay do you notice any issues?

Nope no issues seen on my side

2024-07-31 03:44 UTC, zackbradys commented
Glad to hear it! @KaminFay

2024-07-31 03:44 UTC, zackbradys approved these changes
I was finally able to run a few tests and LGTM!!

2024-07-31 03:44 UTC, merged